version: 2
jobs:
  test:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: "Package Manager installation"
          command: "npm install"
      - run:
          name: "Run test"
          command: "npm test"
      - run:
          name: "echo hello"
          command: "echo hello"

workflows:
  version: 2
  runTest:
    jobs:
      - test
